### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by jmcarcell** [key4hep/key4DCMTSim#3]
What's the status of this repository @wenxingfang ? Is it used by / useful for anyone? The README is almost empty and there have been no changes for a long time. We don't have a spack recipe to build it so it's also not part of any builds.

**Comment by wenxingfang** [comment]
@jmcarcell This is a repository to show an example of doing drift chamber waveform simulation with multi-thread using GaudiHive. More details in this presentation [https://indico.cern.ch/event/1076542/contributions/4527626/attachments/2308522/3946029/key4hep_MT_20210928.pdf](url).
The conclusion is that EDM4hep works with the traditional multi-thread of GaudiHive, while for Gaudi::Functional, it has a problem (unclear and unsolved). Besides, how to write the data into an output root file with a multi-thread environment is still unclear and it is a missing part. 
Therefore, one can use this repository to reproduce the results (also errors) and have a look. This example currently is not used by others.

**Comment by jmcarcell** [comment]
Thanks for the explanation. I would suggest two things:
- Save somewhere which versions of the software were used for the study so it can be reproduced again in the future. We have one breaking change here: https://github.com/key4hep/key4DCMTSim/pull/2) and probably there will be more
-  Consider the archival of the repository, freezing it forever if no changes are foreseen in the future. If https://github.com/key4hep/key4DCMTSim/pull/2 were to be merged then it wouldn't work anymore with the software versions that were used when the study was done, so maybe it's better to just freeze it in its current state together with the dependencies.

**Comment by wenxingfang** [comment]
@jmcarcell Thanks for your suggestions! Maybe the archival of the repository is a good choice. For the dependencies, do you know how to easily figure out the dependencies and freeze them together?

**Comment by jmcarcell** [comment]
I don't know other than inferring from the dates which versions it could have been unfortunately.

**Comment by tmadlener** [comment]
One possibility would be to try and build/run this against a current key4hep release. If things work there, then we also know the dependencies and their versions. If it doesn't we could try to "iterate" backwards on the releases until we find one that works.

**Comment by jmcarcell** [comment]
As the purpose of this repo was a study in the past and I don't see much interest in keeping it up to date, I'm going to archive the repository so that it becomes read-only and it's clear for us that we don't need to update it or tag it. If @wenxingfang ever wants, we can always unarchive it.
